apiVersion: v1
kind: Namespace
metadata:
  name: staticapps

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: staticapps-deployment
  namespace: staticapps
  labels:
    app: staticapps
spec:
  replicas: 1
  selector:
    matchLabels:
      app: staticapps
  template:
    metadata:
      labels:
        app: staticapps
    spec:
      containers:
      - name: staticapps
        image: hub.eole.education/test/static-apps:v2.0.1
        ports:
        - containerPort: 80
        - containerPort: 443

---

apiVersion: v1
kind: Service
metadata:  
  name: staticapps-service
  namespace: staticapps
spec:
  selector:
    app: staticapps
  ports:  
  - name: http
    port: 80
    targetPort: 80
    protocol: TCP

---

apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: staticapps-ingress
  namespace: staticapps
spec:
  tls:
  - hosts:
      -  www.apps.education.fr
    secretName: testsecret-tls
  rules:
  - host: www.apps.education.fr
  - host: apps.education.fr
  backend:
    serviceName: staticapps-service
    servicePort: 80

